---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: ghcr-secret
  namespace: open-design
spec:
  encryptedData:
    .dockerconfigjson: AgBVbXFeC9F2s0H5Q5wfZnen0njWDWZ8RHUAbTxOoYySX4QoVLR6mtVnNkzLltc8OsFH+F10qyQ2ZpOdszCQJDdUvpJyHFif99lTTCI7++v8dP7qFqme2nivu61uKc4ElrSgAR0Cue2cKTwX90TpYzTT1tsv8C7Jl6HsCesa70f6QwmQd5lNEDryoTW7lCEekI+fL6M7iCrIk4M7HnNoYTCiiwXn9eMs3paSsEi+sAf2Ubg/sQzAcN5dwYMs1vbTkLMVnBNVc0NZKyGC0PwTnPSvfx+vi5fAERiBMyD9ZsgqlZ+oR+s8mlJ6+QZRjKxBhTdJHOuOtNO5J9iB26jtv/MmT7QaTQzxOBhsyXrHJgpk5fQpsCogvcT7m8/a9uSEaMWZKP0uvVLx83QKHQtX5f0Mfpt09WXIuKBO+nAIiQwwwOdNFRbe2jxeQItcRILjoz71FV3C3JQ2BjIWck41mfqA09TbkdQFszBQv6Gl0vZA53Jzj5D9aCfqqmlnbixcGLjLHJMseXrqoEB5OCuzflaXgT1N4Gi1Tn3DQIuGYEM0oDmMKxQ0iyjoFL1cvoSoJpplXHKiZxSDnN3YcaVz4jXRiVdWI7c3G5PgjW3XJz29x2BO2VFM4CqItLoas79dkviRQqHDILo97HFQZ/zGaY9YeGGtKn6eAVZRi3/+iH4NbWdHGLmkF2Lus1DUAcDjWl18rbEB+HyMt4LGzLjQRBnIkF858VyFWZ83AfFiC2scx5h26UTU1GoFvGKXARN/CAbRZVMiHM2aBP67Qr2Mmwe7Ao1PIYlYXsoTu2EQJ6C+8cllouCKBw7YnXRGgDhkWUn2X+/fDCPdqTB2bQHweC2NGjRd3gSoJiHa0y9np8baXc8UT69Xhkc7OYN2w0+qJMw/IUalVH/3JJdQ6hEyGbamelRrVdM6iI2vJE10UU6dkv7+EwqVsAr7CftABJlkF4V+m2n5qgQ3Xy0gcIqyXmGnaNgEQVZnlc7PhsljCiSzbiPA2R3S0IlG4VCRWGXM/1Z2aeHIpfW3xK4Ht/bg6gqT5M6/ajJArETMsioKUiKaZX1S3ABbO34QVi6TYAY=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: ghcr-secret
      namespace: open-design
    type: kubernetes.io/dockerconfigjson
