---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: open-design-secret
  namespace: open-design
spec:
  encryptedData:
    OD_API_TOKEN: AgAIRN/Rgg6B1r5Nqv/Nu8T9P6fwAvXoyUQi3QfSEIXQolmI0zvesKdWAMq7z5Gqg9bP0tkHAJRbGqeKu4OQUAB6dKqP4t19xMSHz//55HCrjYs7KodGR8f/1b/UmNwLaJMFqxTR27fa5UKIb3bL1eug76MOzHgT7tdZTvG9O7E1b3qLMa+bjK1xF5NhcnCN6T6Hym5Dp6ifGzPAgbZ96UzEiVp44SSLuX1QfT/VklKXQvJA5pMdp/+Zs2+Nc0ivdrYZ4mgzmF7EsVjvCQZCZGdiGnIpd2U4+Vt58mSf0CuJ6eCrr53CWqgdzIQNt+2OXr/9C9u1INfKCIwjLZjIAGxGlg6vu2QO+NSnk99z/phropDH24r0jL7TOEFs3SRj8Xuh/DaxN+wjlaFH6G5zRAtFo1Y6PTqNAYZUnYUgSJQuTn5vu/yNEGUwFh3ehVPW65kQcw8/rXc+x+MVz4zPJ5GO4jtAcC2cKljpr/p/omYuMTy+KdoyM9UH22P9JVVLLw5YJU9sQjLgsKFPROeWJt7CZzPcdpsZDC2hS4U4vxixxkbF4WvMjyu1h9P/qiSrrPws/omImymebBH2PMPOTnRK1o510G2RjFFIgZvWqaoqDiWsM2xGIEZv8aChF6OphPkgwuvYcU6Ugcezn5bupHPy8vy5lVvt3wIG6osJzU6vBPNn9JrWqFt0LIeXUrLxJL9MZf5az91/gA0PtWDFsS0ayAyZTCq2HhHUV7V87XoANkz/UfOFn8ooIESxQGe7nhbn1VbvZV/A0TIuaJliPzTG
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: open-design-secret
      namespace: open-design
    type: Opaque
