---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAEKXEcDqocy4P9qE9KK8a3QKBLxXTKKeExqhmV0aJPt/H4tJKvPCauiZHWFVyrxFNG4WrjLeG1lU5EoLO94Bkz+NlZIU6JFrPdc/2nWQdTPlOSntRa6YK7dFTeY+2au8MaDYQG3FWYjFk/eKDSqXWa1kpCmnjobYNkHf+dttbpqg0IC8wWXx7O9N5/rr3TcZjKtYQpH3vaswCPxoMSG4VrqAmyclvsj2LEVPzLKU1GO9rVQJ7nkdRFW7hR+iUmw2JUkFhuAaBqRUZyGlQsKypwCWI+0GG19NkSh7PB88TfG3j24kO7vU/KPXtbSX8x4MxUnFoko86T6IdP6gwNoyTPETAUCgmwJRbtzXFXIq5LXjE6NIpIcqBAI6HcfLTRk1F0SgORpTks3Vj1LrTK4ANRzivLpApS0grz95emHFGCL7yegrC4BnoMMDIVb2ATxyoGXpOHuXCIhDV7NDa46XNiKfN9/3Yu8vbUc0kF5ZvOVgCc6pDturCj74WENW1etcnIqqqe0IdpaBZWlsTzQ3MimTP/nEvITCgOmBrAfAEVCqkavXm9jHpuQLYfuTM5jbjXw0LUcNjm46B2m7utLjNBqGndcuU0/XzScapmHz0odEEgQKSo2p8sIfKjZoT+lCu3tTXbmw4OIO/aDdM1NdGF/W7XJ402gVf8GEs0EGrILGuxzRDNP/hOcbKQpG71qnGwOTM2zOcDiNbp6dMG8IzSsl3Qani7Apc8DDgVZUmomckPnIUzpgAk
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
