apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-db
  namespace: vaultwarden
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 16Gi
  superuserSecret:
    name: vaultwarden-db-superuser
  bootstrap:
    initdb:
      database: vaultwarden
      owner: vaultwarden
      secret:
        name: vaultwarden-db-app
  monitoring:
    enablePodMonitor: true
