---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared-tunnel
spec:
  encryptedData:
    token: AgAA2aZ9jbamsWDRtJryqKjGgCmqxkSSXekqaWDvdOVjd9TB8O24Khq/xuWuGom5YmNpPQ0rLGjekUdkxqo+mhAAgv2aB9RMd0CNv2sAhkHskHhYDYfdcrvbGM8M+CzcAs3gKa7WTyaAueMs1XzqDDyoHeTlTJ3x24OpkXpmRh8DtsBwHpLGpofV6Rr9Yo7rQYUEorBMiq+eSRRm2jC8CqTAhkWK8ZZetzh+5tx7fPjX8ihE67bUCvqPnUSZgI6LvgTfXKKOnlvX3iQ+bsxWskzUinPBiPnjch1Jl5xzPjQx/pLywX1qIWvr4jN5UP68abCPmwk2/+B5pod04wZUp90K14CqiIwr9l0qoQ/o7HfHRxMze4iloHlZA1KOqwtahDbw6WWTNWHRjcD2qparpn7VsAoxU7Ah4tBdxEjbF/1rDbtimvOVaTjudvYR/koBjmL75AAgE+3pQBK2qJUAkIsIFZcwIM+YSUl9sKoWVgNWeLns/dC6Sr0poWEaAfu0uSp3M0cvYRzILxgHJjOAWyV0jypLDt3mLGm96VjOnmS4S5xWxQ61ADxT7GpEozRHfp5upZYUlBo7QHIPG+/ZpLw3CTUi20lajZC7Hy9+C08fET1cOkn0mjhLb9GaHQsFhnQY7gZWJGP6z+7TXcAJM7gFjGznXmAyuIt4telTSBnQjga+E/f3gdBRAIP8gxNUCa76rhq5z6aZmIRiuMAmkeVDEjSmjfQg2ilbyHTvFCd+qnrdaXKJkdf0jKCYR8uYDycSjSejMwvherGzlOh+mMgQBYshA6SBTuSN+0ndIUk0bN+Xjtoq9nPZkxB7CH3oRy6GcJ4PrPxbiBZNvGYU6BvruWH/DwV8HLGEVVYuZXq/orKm5O/0UOfhAdEbubmNbFsP3bi8TBEcS5HMDHGG0AjHngReDU6pffoPeguwNz45ydrdhdQw6Lhw
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflared-tunnel
    type: Opaque
