apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  namespace: searxng
data:
  settings.yml: |
    use_default_settings: true
    server:
      limiter: false
      image_proxy: true
    search:
      formats:
        - html
        - json
