---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: searxng-secret
  namespace: searxng
spec:
  encryptedData:
    SEARXNG_SECRET: AgCclH5W/VUEwL+Y939P/S0V73Lwy6S4uKJwYXOfewPGQRpQlufBCb5FlTlHkhiBVXaxB6/0Rk6XMM6U/DXRCG8K0SN4v60KYOfkqPLV2UZDtP0CueoWK73MUyOWWoxSYr2KTxZfVrxAXUkNPb1dlorAnek/VdzL8BxVZiDTexyXujZ0k3kexHMdcZK0IOU7xpzitlERZ+7CEC9ghtSXgKTbf7B3Z+/BBr2MRaLdkbR6GJxEeewPx788RJXNUpjQj4ldGpa8L9mTA8SF42v/k9wFlYi+/8wmbbXfe30zqT23uZYg3tnHFYL42ffLls91MCmbQfAJE3ZlP3X7XxIz7N5O1qsCRc+PfKXsgcPNEJlqpZM54tMZuapp1pyUOjBMOR7aBdvn3KbdOxohaWyP8FDcWX0RlJPWPHQuURu7Io7BqKZB8xIrNbXcqUxwekxtpMpYJG+l7vQ5vpI5dpyTlQv5EOneUaFtNCMOJb7lrx5bM+jvPI9y64c/B2l3EP7DKckkozXSmDRmSGJ/hSjMrGVqaUBFfMWgd3/62P2VlZH2sTT/73cvvsiVM4cKpmL6UWMjbF2kyqa9DhPQIyGO3bdImg1cayXMb1VhtEdlCMZCxLF3WkZpWiiM4k0nkioCARzUYeVgpvEVhva88vC2AwekQK0dz8GkFNx0cSNwwDKbYoN2fAutkrS7XV+R6lgavQyxGjTxa7Y51i3GCGEfGhxxAjxsqV0ovY1AOq2MFOPDNa4ZERPkK/bn6m7zJLyf9WdBPofr5XGNoiHvhPObaeeJ
  template:
    metadata:
      name: searxng-secret
      namespace: searxng
    type: Opaque
