tls:
  enabled: false

auth:
  cookie_secure: true

mqtt:
  enabled: false

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 10
  detections:
    retain:
      days: 10

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac

audio:
  enabled: true

snapshots:
  enabled: true
  retain:
    default: 10

go2rtc:
  streams:
    sara_room_camera:
      - rtsp://{FRIGATE_CAM_RTSP_USERNAME}:{FRIGATE_CAM_RTSP_PASSWORD}@192.168.100.173:554/cam/realmonitor?channel=1&subtype=0&transport=tcp
      - ffmpeg:sara_room_camera#audio=aac
    sara_room_cam_sub:
      - rtsp://{FRIGATE_CAM_RTSP_USERNAME}:{FRIGATE_CAM_RTSP_PASSWORD}@192.168.100.173:554/cam/realmonitor?channel=1&subtype=1&transport=tcp
    entrance_area_camera:
      - rtsp://{FRIGATE_CAM_RTSP_USERNAME}:{FRIGATE_CAM_RTSP_PASSWORD}@192.168.100.172:554/cam/realmonitor?channel=1&subtype=0&transport=tcp
      - ffmpeg:entrance_area_camera#audio=aac
    entrance_area_cam_sub:
      - rtsp://{FRIGATE_CAM_RTSP_USERNAME}:{FRIGATE_CAM_RTSP_PASSWORD}@192.168.100.172:554/cam/realmonitor?channel=1&subtype=1&transport=tcp
    living_room_camera:
      - rtsp://{FRIGATE_CAM_RTSP_USERNAME}:{FRIGATE_CAM_RTSP_PASSWORD}@192.168.100.171:554/cam/realmonitor?channel=1&subtype=0&transport=tcp
      - ffmpeg:living_room_camera#audio=aac
    living_room_cam_sub:
      - rtsp://{FRIGATE_CAM_RTSP_USERNAME}:{FRIGATE_CAM_RTSP_PASSWORD}@192.168.100.171:554/cam/realmonitor?channel=1&subtype=1&transport=tcp

cameras:
  sara_room_camera:
    enabled: true
    audio:
      enabled: true
    onvif:
      host: 192.168.100.173
      port: 80
      user: "{FRIGATE_CAM_RTSP_USERNAME}"
      password: "{FRIGATE_CAM_RTSP_PASSWORD}"
      tls_insecure: false
      ignore_time_mismatch: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sara_room_camera
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/sara_room_cam_sub
          roles:
            - detect
    detect:
      width: 704
      height: 480
      fps: 5
  entrance_area_camera:
    enabled: true
    audio:
      enabled: true
    onvif:
      host: 192.168.100.172
      port: 80
      user: "{FRIGATE_CAM_RTSP_USERNAME}"
      password: "{FRIGATE_CAM_RTSP_PASSWORD}"
      tls_insecure: false
      ignore_time_mismatch: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/entrance_area_camera
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/entrance_area_cam_sub
          roles:
            - detect
    detect:
      width: 704
      height: 480
      fps: 5
  living_room_camera:
    enabled: true
    audio:
      enabled: true
    onvif:
      host: 192.168.100.171
      port: 80
      user: "{FRIGATE_CAM_RTSP_USERNAME}"
      password: "{FRIGATE_CAM_RTSP_PASSWORD}"
      tls_insecure: false
      ignore_time_mismatch: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room_camera
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/living_room_cam_sub
          roles:
            - detect
    detect:
      width: 704
      height: 480
      fps: 5

version: 0.16-0
detect:
  enabled: true
motion:
  enabled: true
