---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: faris-website
spec:
  encryptedData:
    .dockerconfigjson: AgAsfSO6WHF4Y19T8/cqSWsvMaPzM+DazGohP9v0hU7DLjXIZzwxIGoesuGMJtnoiaq70I48l72ws7OEB/gPky9lBss7o8nsAmMvDAYn2aVlTZVoOEN9MzBpIT5HdFkLAPkGbXMmVRH0D5j5dkJpYIFtMLQYs8yY1MNIrGOKRYNJNcVp6Yw8+PiQ8WRRXBphAEf7OODR3BDXk2TUAaTjnseZ3GOsDKUrTqeB7r0rs9MS0aOJLLfNhoj5lmnJHv0LTq4I/b+4EUGljhxBFAM1wojvF10PBi22/cCTBx81p5y53n6fr9NJ81uGZTTN07pnFlEOmdAmjbHcCNVV4GKjBRKeOpULGzI/mEcbyQsW8fZ5fsOiAgVYLrfV+t+Z5c2Y0658dZt9Oci3b5dSq61sZaUfd+XAr92pBKz40Asyu8iLPaL8XdhPZSFN387i92WUwqayLzHEAPH02punAa7iSV/F/0K6IIWMonHr/USUcjck9QmqJLbgW2uPcy9YF+2Tw/+0cx4I/4Gyw5ZEVgWvXccXEzUFTyQu3x1TMRYNR0BUHX5usRwGa58uTekyh5WgYd2wYplB/XZOmFAKuFhSm88uSFGVbgxgVe10UWGMZd6r4+Q/SYFUAOlWjZhz7Oy4ay/glg7PgxQpSAVsvTdHYfOXMgcFwfTfcDfyE1zWE9Y72NW4Qw0Crv454PLPJPs4OT6LSHluWu4ZH6xu3iyDDgjf3EMTm71i1I1iuzq9EtADUTncLM1vfNFY5MOPhlP0GPndrHwcLdvfYkgImddL85EF5hj7nzCCaDT/XqJAAwLX9Nx4s62FeB3Jb4CstJ8DXn54TJECb1It4xjypteah4tHjMGaxQPP27wAa8bWLxfP2EWTZ9WX4oIUVgpR9/hVoUJ1J3EuJmkQCY3n1gmaWCAW9Vaus30y60GBTFjbIBsYbvY9Q5CQbZvgJa0tp0/pRJPhxKn3cjw=
  template:
    metadata:
      name: ghcr-secret
      namespace: faris-website
    type: kubernetes.io/dockerconfigjson
