apiVersion: apps/v1
kind: Deployment
metadata:
  name: faris-sanad-deployment
  namespace: faris-sanad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faris-sanad
  template:
    metadata:
      labels:
        app: faris-sanad
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: faris-sanad
          image: ghcr.io/faris193/graduation-project-docker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
