---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: faris-sanad
spec:
  encryptedData:
    .dockerconfigjson: AgCFZ0+6SitxIs7eUWBm8/CCU73u07QiDbzs7YPQyuoxmR0PPBONX9c4xuKzeCSOJt7qnb6yqHLojhvUEM16fRLmR1mKboyk/GOU1zNuwu2+AClOWL0AEXic/XkwJDKd35+HkghyHp+c2Px5EEzFFlBO+t0FLCbHRniaiGkJPT+dvIjX257r2cTUaoBLgs1bRxbJmvFWV5rKCegHL8WaP9DthekBdE6BOOpOhGzye5bTcsuKXKZNh6f+91FMuQegiokY7AE11PYouv6Y7z85vg3R6lNFWURdqgReC18IrAjpaFed90PKiEPJrEkO6KMGDdI0HHmYl844sst3SA9XWWLUEYT/VPSP6KppmCBjrSVYUGOfPT4zBEVuU0pPmebOnEjiqp7i9B1k7jDggmUv6Hom9md71a5XOn9MFEXo72LNzQSXuxJ5M8l3sZ5m52SMOwTBPTJHrvhEvWyvA+F5pTdhRoMie4XJMbATVi26jS5VuHigbCmyq75NfqE91i/PPyB5RTWmpcn8m5zLSSyeVgibylQJ1dJn8HcjdocKbeXJ6SKvhO+1pwTRr/jUd0sBMkICyHSCtA/+WLfqxH4RQxcls3lEeyCP0P6QXz9WjB8yZMDKM/lXZdQTThl0KjTOetEowmy1ICwwntFt7ekQqyaEKEeovm+TRm+FSTSO1SPDVpXyadcB7ONQdx40OdjqLuaecWdFpQUZwr0hNMM0021OQk0wuV+qOh8XM2LvzgTQgVnvO/miFM/sbUazs2UODPi1Zee0ZlB0NktT0x5FbeKNGSeMhiAKIgcVYwLVcESSH8h12uKgPML/e3cUr36SVmExuwV5yhQr2CFu76fEdnAZvSVUdiSrmY4YagwmNjhNg8HpbQm6TBTG6pw3j9a2i/hO2lhZWatqDKomAdZZHEHzihhKHoFe//h7HMFxIqR1gff7h3DhfIKBWPUsgY1/dRvhjKes1dI=
  template:
    metadata:
      name: ghcr-secret
      namespace: faris-sanad
    type: kubernetes.io/dockerconfigjson
