---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: faris-sanad
spec:
  encryptedData:
    .dockerconfigjson: AgBpSLB6ncphUcU7bPhu6wpz2JUE2fhGrLk03hw/99zd5/lhMfZvIvLU+39E78iyy1ssREZ6STqZc+U63qMSGi7xjQQTkciDnwbxURShg5Xsb+5I+zUtEqXi1BBnosvZoImCAiFXNGGE2Bd61k3qVdnPsyhF+cqe867E6og6aweHFCy5ELk7ruLPhUggdPah4srKWNiPJ9J8Re1s7+hchMxBj2Q1Ae6e0NSpb515OM5Vs0trT9WpUohv+qyMY0F91D8G+N6ro/slUgHusBSKGLQrEQ3ll/WD4WjBi3qj/W6EZxSZh0DR0KzaevOB6Ep2r39NKgqlfLGsv3WX9BzK15zVbuFsSbxUBb/Zt3hP3xY55XymYVtgrLgk4uOY7S3hF983TFIQ6a/p79B3djAqjaMJSaRN9KvdkIFy7Ma+Onfe+/9z3oIobwJPf0BWFoxH/zb+f7PAvbdUvOezVbEOE2RYB+JVBmTwoP7uFplkXFZO07O60KpOaNBfQNxYQW0jB96f36lP0T7m2WNag7waXLDsEbqeDAQpoGyFfh6frJfDAgFDCA7Azg8aK6b4UoxEtsDDmyl++xSVElGT3kMnuEKIh3DpSlQALXg2YHY39PYHdDMH++sEJMb1fqBmKF5Mgq0fpiFoUcHo7bmX+EkoTJRDbBlc0YqeqGEjNYZGALhktWv8/gD371hR+gZWOFieabYshtmbrf3LVA8JV4i9mAb1uqAeOPM45yv8rfeMYBJ6l8saqdSNpiYQPI8a4q1l1Sgal1k9QQnyYALkX4G6POKwgsAkl71rvgwglxt4NqVDsTWz3kY5042hrQDEPLrmgyEpMNJl0oqcFuvtVc4RTuEIv+OmpUuG1YSYnZmf9XUAZnWBMR9jvSatd4OJtht7r20n0fEoKY7VzCWj6HsY27wcPb/Py5GexmwDPp3OGBcFWBVd5fNvt4SU+LWS5Z+90k5K/hSxEtQ=
  template:
    metadata:
      name: ghcr-secret
      namespace: faris-sanad
    type: kubernetes.io/dockerconfigjson
