---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: faris-sanad
spec:
  encryptedData:
    .dockerconfigjson: AgC4g6kgYQf9L7jHuR4TG7CWGCwRAlZBaIMCDCUtqph5EJDy1PnQN95U5sO4CM8Ea5dm7a6TUL0Ybtv9tDCryQpEfz5za2VIJpLGAovdVbJZI+9L9pmFVFMw3jXirR1JxspxnBW2flLmgqPSdPRXSlueMBALnf3xl8qeu0aW1cUZj0649xxhpClj5lFhGLTJHWF86J73I9tq3cvspav+zFO28FhNaezfokkUU2JQHQs8+pOpp/algMYunAMy1dYKdOvEIPO6Oi/jCnyaJV68eojAKDhJW4N1sGDzHtcQTYHkJwgBKChaUNuTRWxJ8ccI69PNwnEHAwaGnHxEzJqgYv+hbJQnnTf+P/Rq5TiE+3Nk/wJ5VAJoJj7846bGQsgwHGER7rQmXlSBauSEudPso2RW8rWzB66shMNXvJxmsI7XC3z6+AkpZ62rIPawQp2RD+bd8B5avvI+GufYy54S+VkI62IOKoG3JQN41F/LsUdDh6RN0/wOpbM4Ps/x2KcCd00bqV961dRr/MilbRsCvkZVJ3BWbGF/llu0Fuc8VGU7eSAGqcU4DYOVNG/t6WlVvjRYc45a5TtjZo2UHZZR7PkQ/fXk1q/PcmMzxjpfhzt7Ngo11ECOMKHISaGiQTfVf3P4Wa9/Nd7l+8Fg9AbiQ7RCrY03yUTC7xxL1x3TdDHQhf6FEpEwXHGcU8II8p7Lym3ghWXO5VRjzEuuXCy0N/fJ1pbPoECk8arHNrJ+mHOe6JOt1krurpex24ZrMwUu0WcBnq3qc9S9naPYYNDr+ZS1FLEdUhgDu5eKccnlHPmdwxYz2xBIiZWDQ+blgYwm2E8bU8a5p7u3pBJNt8iChXhcnfcXcbmES/4TC8FlQi0ZNpiskx/qypruteXVmOEldx5iiIhCD4re7aFAE2DHQHqjRYoUt2qVNhEmqlJnbb24f+89HsC8wl+6qu+yail7QpjatOVaXAw=
  template:
    metadata:
      name: ghcr-secret
      namespace: faris-sanad
    type: kubernetes.io/dockerconfigjson
