apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sanad-pg
  namespace: faris-sanad
spec:
  instances: 1

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"

  bootstrap:
    initdb:
      database: sanad
      owner: sanad
      secret:
        name: sanad-postgresql-secret

  storage:
    size: 15Gi

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
