---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-secret
  namespace: rustfs
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgCUF0i0rLJdsPAeXZiD0DArgF2h2Q9sTVRWyakdLTHzq1Ns3VaE81ev7/oRzGFXNfdf4qe2rGIwVQyIfSzQiPGE6J1SXPt2omVRAJkcpLmFVJ+COThEVxg8r1d+QOLT8BK5R0KJUeWjJQUTVJgx5aZViTJuA7g0DFhPf87uqmPfodnPipNUnTFm/SShj6rNMix5BHFpNv9KlIPGJNB1nb18L+wAm7p+XaV/794Z0Hc2/0xfuNcqreI7oiTSpGBOfpxe5qvzKtunpUxLd+3uUhQfHUVJdS/lpKUBukaKYMLBq/7jzqGz38i3n/f0r08BrZDaFcUs+BrFnkqtvoTFjMGfacbI7//+QqbQQXx631tFpRr1k5ZHq0Ale35DdxLacfUlRUg2Safrc3qowWs4zXkF3xbhOic43fsq0mf0gE24teDftmixBwkKj+OXl4Kb2SmR9qN0oNa4otpHhzYRM+K+WF+19M/eTu4+uznCkRvnJM9P9wFEDUUDvHxo6XCImAklCdq/AoYjGH5aO6UiDrJocszUS3PIupG6DzgkMOaAHKIytxHEKUoY9UCLavwkHB7aoukazud7XkofvKXbiyCuQeIxPps4h5HSs4wSGa/VVmemPZRizVgiiGakWgFLbkFi6gN5PZyIY4ivgs7ZK9NX6jQhI42wXfn7UmdCG4waMErExVynBaaJAdSPW9x6LgEskAJdhZ35xWzcILX+ies=
    RUSTFS_SECRET_KEY: AgAP/Vn/SWXWHJL0f0xVWkk46cciK6MWWBiAbq67Muq1qX+yk9Z9S+4rP6c0Rn82TT1GRcQ11ghOwFOYD6sO1xAym2iJzESNRF6kZt0VR3oYJ3to0FhRJjcmGDeXbWBHwij4MCnb1Z2pkD8aSBHJrM9a6XnjP59glgaOFUfDG7GQ8WBL3/gpbEMc5LhHFOo5cNWWK3o91fSH+NLdhqWAxU64r3QwT9Aj/GvE2nO/qhV8gw9DBhYLlB/iYJiQQnYvG2x2SLH5FDkQuoYyTDf/cgw1y6TvdC7FdTwU49m/HWiug8l5FM33uhBsr3/EwaSwpi0NjRuSfzcr9zBy8SUWnFtuRAZtv7vL7sSb+vl3u3DkpVQKmMwGtdzNzKM2IJKTRdUKxqMYNr7YsWLI9I9KIikwmPcyFLK6mwHENDujqGCwLx9Y+phN9dTAfKg42oPU299kKAVRf/n8Okrzp2t+Jcdk1Kss9CzGqWggbPCD7e6wJeL/DchATNy0C2fyDssS5pMTIn/gYooZEX7s/ShXJZBN6z3F3ZfLHekmbmbHF70eXJY/n9u+nKBWAEocMCZ3qiBPKi+EMA2JYx31rtmTQ6AyAdQEtSvcbEoSfq1/nMNhNG9lafL7vky8FCVnWAYMIdOCnZ43ePsPSa6ubKqQx9DzTI/Q+976uehnx3nRhHcH+j2kaIpdSpIjNc6ZqNWhtzxaXX1qpkO9GlPo0Mhe9ns=
  template:
    metadata:
      name: rustfs-secret
      namespace: rustfs
    type: Opaque
