---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: faris-sand-cloudflared-tunnel
spec:
  encryptedData:
    token: AgAma9WdxHRWoRev+IvGR0bOdHyMMVoXHYCBZ3Og1CCdY8GhL2Jxy4GHo8hpI/XkjzUFnMTsfzslb2a6jyNf61yiJvWaez7aSrQuWUHPXg5usN7AM8bY3rJtw6k0beueE6S6niltzeY3kpuPWT9WSbLdBypNAt8dqSJ6qoimwfD0ZTtwmdYCiZAoBzv+GS7raaJYwD47NVQ40nLd7iPv6OYfQgAbRbOUIdW2TPB3m0DGvWpPAeYHJB3pwcFGKgYreX05nxg0Y5jfdVu06jkp+BfjV1W14d5Kqlg/bYuz5MMBn5wQwPlYlEHCYhHZQmY0wC6cMWXF4GxJS5nxo/cENOgKcZkJz0aJrF/HEI717wv/LhCAQ+tG7uegjA9LzMVa0KxkEBNWPDo7a53fgHNXe7OJbkFmNkHTJV9Ba6eyWRBY2g8NcG2uEVrKC3ULvqakoHgMrrPeoDUilP9JYs1WV1mMnFQX15KUlP/UQEdWUhLmgGT5TSEN4TJun4iPmoclmVI/EeJbgyAnYNhjHZq3fJ725n6o/ZLjfBb6UfNgAh28ZGKBKxYuoz1clrUb2eFLO6lkH5kFxBBcvuldB4nZuZxUEq0BAhL8YCR14ZgrgUVXaJ0OpS7MvPm6OFkh/kz/ZRQBn2+m6sF38Ub/QFURoQciRCQzJQBzgvyMEyq115V6fDo1qC9iO/BSp1Lj/2L/uKjA9qQ9aDkcv5UnG2hU7+TpEg98lZ5liuCjAnTqBTJJhp2ugSE37U3L7LbsZX2fADE4kppWa4c1U2+7QKUhvmFju8Q4mbwH40jSLMbxzP55YMpmRJwimC5GgtNJuzvrJh3wWtddimpDoi6otFVFgvKroUx4Ix9uVwlz3bC7X+JaeQcPCs0Jh8PQdY1naSn7pkXqfdXiIyXr5uBqvQ0VbxGawOfzWQ0Ad6zTDKYQ7YYH4Q1HMCqIu5MI
  template:
    metadata:
      name: cloudflared-token
      namespace: faris-sand-cloudflared-tunnel
    type: Opaque
