---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: honcho
spec:
  encryptedData:
    .dockerconfigjson: AgCD/FhO9oTLVSVSjYWDDYbVio7pvIy6004RTgOhdK70sh7F2lO2401jPBnpOQZHOZhIiJgQYtUW5lPmkymUmYGwPu20V6oHSI0JkAO55rxoJ3VSLxfmNMMMDs8rCcnTfyALiLugO72Vl7B4kgyslBqmrzw38vsNteIPe0dc2r2uWDf7OBcFkSnQnGMwp4aG/vsjZhd8lhY2qVFJX//JY5XNAgJXnL5grnDCbBWMDDF8fvnPKygo/GyrVEvyjIcks43lBjh5EXZ0WKsZ1mu1/G2dV5mWl06ZUnJc3kPZpolFUToZ2HhkDPMQSPranpqXfMOCSJCOUE9g/VxifnZWNx+tLAf/PbgLXMr54LmXWZWYPaXY1yui+nm1LL0TUoYxrtzPSz4QmCpMvImsIcbOSNqAAXxmTyld2QnthBd63COVKyqM08HGzpwp54dPdVM0BblYrrHgtG/m7Wb5op2P5SgXUZY81/O3IRaOdbpxbM5+5aQ3Y9CeHPIczMtljGrVFUc574/kmpz6aVckAykVwU0XjzfwJLRmQTBAvTDDNrJIV7eAdQcrw0celZXhnY/h0QwVUJq0k763DvaKBaBrj9TSUfTT1v7zXVUCdjXIED+RbBIZvL5JSl17nfSeLbb/okzHJZgNVYZcs7MXerIm7Tri/xVMkCd02DxPDc1CPWnp0E8vnBeP7Q4ReenkCVfSRpWCIw1t9idOKv3Eum+Zkwkp1mBx/ktdCfyR9KZTnzakDOy8EpK/ZnQ9YC5fIRNWEZI0pSdQzxw+LZgTCfQODplFI7HV8WU+fO3tuM4i/dMVoyTS/EYP48cel+IiMy4B/+fnPTz9Xwp2qKDTQG0kI/qKt1dgyLXLLuRdV+Y21XoEN3v5wbzEHC9nurAEbP0QRHeq4gJz42uJ4RGOhP1YbhmZVpGPkvqo18snhynPrJBYs8WxcuV+DjbzOuWIfnsodVjqKeIg6kb3Slbg8GjUi2D80KD3fEHpxQHQb/Yoro1jRioaxmx5J1yQEeWEYWR97oNxTIQd1uMmaHSAtOn7frI7sK3Zg4Xvk3yzXJ+W+5NYph9QOK9HwQYUDCb/D3s=
  template:
    metadata:
      name: ghcr-secret
      namespace: honcho
    type: kubernetes.io/dockerconfigjson
