---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: honcho
spec:
  encryptedData:
    .dockerconfigjson: AgBAozVKs9Yc+SaVJlOL2zzs2TJqiNXV94rqz7bUS8XzsaZl2wS5W9MhxaSO8mc5/Wzt0NOPpQ3YDTLXHAupwMuh0o4KVYK/5rXaq+Jzy1RWLpkYzAIbOVD21D1jGstexX5Ev7hfUEPPyMSRKfG1JX55JyyQW4VNqsVG6FpUgj5iRwCzqRyCbWsILP+2KXBD4pQBvuyCFUG14iLsRraIuHJicqp8HsNsekKx/oWYcayr7A5+6JzIj0d930rHyNFxeR6zcNJBvJKMPqLh17hsa56TYZzrZ/1LaA2+K3jD4xBGyl3GkTWyATbmyPgdUqje3LW8fEG3Mr8n+I04AyVRGOnpzgFKeo6J9QUP0mHbK8+Lp/KvlQUA+OW7hopL0WIjtGmKRT2/JkAaCzY7r4eG71o0PKketa7MHShnZK+DGp8InPNBL1SptbiObJteZLAqqRMv+lMGJgFZz1KJGTQQct5TkROt349rGAVyP/uyNEAIf5R+Y3+yG7bxMqHP4jOfmywkcoFNlF2Kz1qg56+3SoyvsHQZQeMcAwzVpXOtOr2LEg5Lm/HotydgHDcsDGp+D2uoQ4tC6Z7tXcl4To3ZNCFfaYMxh7d0A19Q1Z/t35Pue6Gdn/LieN7ElKrmTQSR70oZ6xsVEyqg2Gme69lBw4jA/pdOU0EcwLQPj8fGKv3NtWVQd7/EalTtW25txTeq8R4b9q4iT60KPLkw8IbOxIypqGKs9xYn6sOvP9AqGEdzEbieEqQP1drYkNBqoB/0VI9fiwoJe8IhcO4EfUhSynfHECvjcR2AeaDud/x/gtGdU3QY3L3PJOc5y6XQoF/iaSNy5vCh8kHdh8kR/APhjy1Gb9yintjFZNTFnqZebfsTvWmcIttqxDLk3G8DKlRjKWXuMVUgFJV5iyuW8WFMJktl+yk4X3ZEsEDV3+WBDQ+QUhqMNESk282SVeXZ+0p0mpzkMkRpzaM=
  template:
    metadata:
      name: ghcr-secret
      namespace: honcho
    type: kubernetes.io/dockerconfigjson
