---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-pull-secret
  namespace: honcho
spec:
  encryptedData:
    .dockerconfigjson: AgACV1btlJs3DvlgKhF60uQPM4/YncW2V+xEHOC6EsXxUaBIcxfil4mKsnkeiJZJ5OriEf9xOV1zRvtY9GH37Ag2VXYrsxoS83SyK73/iaWfhpIIFKBI4XVVZFEHpcpLD6WaiJ4Ux7nKwNtJH8DjxY5yqUX45UJZspltAad5ag71TEyRZrNg+PQQXwyV2ZWmTDUEaH5r4vSt2OCas1W+n+VaLxSUEQKpyGoNqUyIosGm/L//TifOrtKvEcsKBYxuKpBq1r1DmSDbMapbUSZabHEULMJiYLTFAG1xw2szEPrsydTW5HwdU4OK615wZOr5RwyXL8O+rDx+kEeeBF11BF/lfsQH/QJGtM/wUaIyS+s4t4VT8IZE0JPECr7HX6uiZ/jYqSZqAY7qTYm074l1a4rZieMP0SReODlH8kI1nRLX9Hp0se/Lvfh18tXzUwMMcaahqfR5QqOHvif5zPSi+EPsrf/OYgEgKWSG5InzJ/qgvXeycy4+GXsSlUpf2tF5t+fTcUJA7IB7TTWQzbf7/hwdOQkHg12IKOFUqPCNuw6hf1qyfoBvPTX6uDI0g+0DuORdbbmUTx1NHDni+U3QtUgGmgCQrrk6HX+Ll/3ZA3uiNAWu8OMllXS+6rPxX9LPkS1Z3iLq9RvE67wk+pJ+83iBP+6Z17wcTWzZ1PelXBil9hGWDaQmm6Q9wGbeqVTngYC1PaD3J+swd5A6yG3+nNfzGkHmdcrimeIWgwba+l5o/dkn4Bs7fyrC1qsq3ZNtk0yfbK9LGc1Db2+eSw7v6nIdRV7LvNFUPI+k9Qs3GwXnRY+s3AKgYg0fOkWjQsvCfrnm1f1SEfZ1lCCrSQD3cDJG52PTgPlB7X3bzkdOTfq1UEC6F6X9EsFnjaWLFEE+Logb5SEyZtk7DXc715tc7COAql3VFqjXIi2vHLk9QNkhHoOc7ZGZtzyhKgGzHT6bmVY=
  template:
    metadata:
      name: harbor-pull-secret
      namespace: honcho
    type: kubernetes.io/dockerconfigjson
