---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: honcho-jwt-secret
  namespace: honcho
spec:
  encryptedData:
    AUTH_JWT_SECRET: AgBNSxHuKZtgq/UX2v6dBeyd38OjXWZ57DsE4ZmqO84/4RAorZuQBMaxP42Up04OnGkuHFNTbv6/91+xcwBj5OUTSEF4s/M/klMPvfjkDpNCuYtW2rS20FB817qxI1YKmyuU7TwJSe2Xu4/yIEY68KcYRBjPVxwaC5X7AtwiPgn967rld2gaHtsVadWpDxxJVKKAJ6cRu/S9wn+nJxuu9hg26FJ1Ybf3gcctM/1nCxriAjDZiE7e81SSjnUNqbBYmDVc2o3wZTbbRyLI6jsbTSqS+1BW8XWXkgmGix0l4fB37X9wJADeSUAUil9S0+EhXHBKfsuO1PdqmAWIEImseFzuEEUJvyj7G5+e4+jlFnSffE7jGdibS/9sdOc6GAFbsGUcRBv4XdtJGEBv+LXYGa+OoLClTUDCZV5uJRNqZRKrXjlwAu8/k4lyjAOAsP1i9Ld3oAPPpj/oZXZg1F1F9qJo+oMG+MVxjwNJfuxMsTkMEvYznO+T743yPjpKfa/rIVJGD5fG5UzwtCredgyJF5lQT7lWO6lk8J+awUhx3lCed8C+xMqjfGCJaF4qFp3kNW/IuL+453kA/qG/PZX4DNPB07aIWFZKkixZp25leNEb5oV+GqDNYDrrkMzu0K9Do6An5se4GU2Im5SHdOun0b0MQj/+R1bE8LbZoDEOsPK3qGDB2h7fHOozArFnMWd3Cyy9YH/zM2mnywT4bX8RbxJzZ+y8YoxMKWNHWcnlXTdK/Vz0g4OpLcLuGQRKzBQKPERHnvme
  template:
    metadata:
      name: honcho-jwt-secret
      namespace: honcho
    type: Opaque
