---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: honcho-jwt-secret
  namespace: honcho
spec:
  encryptedData:
    AUTH_JWT_SECRET: AgASvVf+vy2pXGoPyR+341RWmSp0+sW6UGjurqau5KHnN6ke6hu0t0tDZtzEoRNzk74B6gJOKxhUy1Tc/ijLoO2h3s9Xtjf9E8MXsB+6S8p+JqNsb3MvgcCLO98OR9qCal9p+rvAb98dc0MmxHegU86ZS30KkphVviq7SO/f9ATGukcXys5PRyDe5qZTriBE1OIXDEcBX6usMYB559lHmLUAjbj697uGbOp9UDAjKLlGP38H33lUeQ8u7bJEXZtpFr1T2EZm9gq8+vQJ0hGGUFtOU0wNcmHgb3K/aGx/z1JvHzZ0++j6U3lRbr1fOQ89RCHa8ZcW9Oh/MiFrW70E69vCMBSB5UKS9vfFBbHcaNKH3U2nG+D+vqzp2yBQKpot03xIPqf//RM3DVW/FuKmT+KnisR5qH9tRegFKuiRUKlORJ8HYiKBGclDZqDQ+Po9gM7j4pMvLVnF6nu4GMUgQq2CEgwTsdn6OlGYRNL5jDSwiGKJUy/fZ7nasiRsooTZaeLBiSHui324UvjLA6Kzwu/znEc8Sv3dOZTDRMgKD8yOP1QOGNWax+wpV0UVjNL13Sqmf5w/drPIvgyLYUv+pu2RaKUL5WeJdULrkO6zSBvquRwnbQo23lekw8ldPgEk7JhSPdKtcI8KR1fmOpuyHZyrbo7HaKcMgQetv3e4sd2KV7hv2CjB0lBnvWcepe8u392/2LkkHGWT+TkDVHBBEHu99qKch8Q44q56XxpCXRYtkCL3kGoD/HzoMnl3Kq/GRGnEAjQyZLjjfwEmRg+ucb41
  template:
    metadata:
      name: honcho-jwt-secret
      namespace: honcho
    type: Opaque
