---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: honcho-pg-secret
  namespace: honcho
spec:
  encryptedData:
    password: AgBFsoV8ZYm9CC8FPoeHoA0UsBuJTxcH1dd3raBLdaVdzEdWFVtryzY4tUpDLAJTHPjNo8b02lbIF30YJmeWVwmlL2YRdvtyWEK+uUe3d6ZAHPGiGiZ3BEZRzWeE71wMB7GxQTO13kvxT1u7yjVHrxLVqWANUOxlXe8m7vATcRyn8b2CJwUGaJ3CVCeYqg28R2LKMx+cmpG/qpVUaPN0jGVZFAQvnXbs8scpSEu3eFHJ2Ix8BdR1zxV1pwTFFS8iwvBknzlrHrR+5N5O4IR/nW41ZKNFjtoxiM1+c6DPIcy05NC0NwQkO12hmxmlMwjqXz6vFsgNxRoQv02F3DhOVu4LivnbB+b5wELSvOavZZVsBIafkWOGWOKiaXPfrklWyQN6A1Sbl1j/ikiHEDMMQt8KcSHNe22C4bFLtbzxNJVOkUQmzIXRJg0rT6U8BRSta/SNJRvlXy5y7c7E8Q1XHlv4qTLMdcAOxCLDFJAup+wj5JPowpIzefobKUd1htz3U7qhzZO8CzCETaeRKUq7hcE2UBP4lhDE97GsEppFXgRfqhtoKb0o5wFYG3BfUpwBCYqI1mcUFAakT2ZV636Dxa/h7qLcUZ8n1iE1y6QhLJocif6LChbpmpozXGq/ahQxNQ34ejD2CnV65I4teojYHDLJwOqzt56gJyyYr9rdMwuLjalICOJ+UumG9hsY9KpRQbRlxVzhieJHYHqmCX4zfRkdSRG24kZ+Sr+59UgQsci2Xg==
    username: AgA6f6XoiTUmTGK38wjgI2MZGaNL71oF3xDY/XapyTDcAQdTaODDp5Zu1mXNy35AcoXMSNlEYLKPEv0MVIVUzFIBOS9tYdCEWjmo/PKolnJl6Am2vocKN/vweguiQWuxqFyxX+AzYLX3d5YyJDFh4YWG4D3C491p2gGKxdKKAdHR3vgSS8eAyuUZStE4ey24uVIU6zfDgfSFJmruHHNQZdi3uRMfKqwwDFwKrLUiIMxs66b6+5T7G57FfyxjCZUZTTX4xph7Hd0iNrToPXdhPEpXfLF2C0tT+BLDFhenetVJt8V0dqn/f0h282GB83WT4AotJvAD/BRxJuiBj4F6E00ShKhu1yMl+1ebA5Ag6B/Ad8TLMiJ0BA36xzcEy9IMNc593g9LeSHst1qtQBx9jPl5ijZEV1rKSwUxIEKNOnBNwxz0PEuHcQGP2/hhTFjq73mRtG7rlCk2oRfYhpULqHbPq2XrQF4wcJ5pxzY6ks6kAWeTeeW89JAe+ptnurUXM0Y2+6lIZjjVitvsRyijQzx0HEr9ZoMjd+A0LbIFohaLMC2nHtsSC7NFZ0Kxiujc+Ot6nBsVEF6m3s266V/wlpEuzfj6WHGhPexNbO1ZJSblqgnxdCeF4pqlbvDdKHMtwMvQkhnsjg9ahqjxJKIZiY0midiRU5HKrGKp5hMx5L9qkjhqdWV7k94wYPrlhuWJcRRf7pRabAo=
  template:
    metadata:
      name: honcho-pg-secret
      namespace: honcho
    type: Opaque
