---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: honcho-api-secret
  namespace: honcho
spec:
  encryptedData:
    DB_CONNECTION_URI: AgAU+xanJtZ+2zRRJc2R7uz6a0lXnb+9qqF9HUswLKJQ7e757y8AEP1TlnD1idX6MhuMCXp6vl8ffta0judBXctfIz/uCPkf5cH+WyvPojcGmUabjuRiB8xMGqj3fMyVoHhCjIl3l3QJsmD/WgCY6MqFDW/5Yw1vI8U0hBdH6eGkaqpJ8o8TxaJOt/q2gpLg9J+7BWFdqBtdaZDi/0pbfyaCHmw0DelF6sfBzxHfwZGKxT9em4e18gNgeZmtttJI6rmQ/cv2PTDSGTtcdmrmH9hPfNNC1iS6OIdAZMwuQtGtLo6fAQ58TmbuT6k5MXVJPNkfYfg5DTxCppTQZUN9c26OHlb5OjHFI7Dg3Oi5UgvMifXid9Sk9sx+uYw+pvX+CfzR25HHPmFKrutAGYp2JOTOISkddV8DD+Ga0POVggABxO0hZWvdJFs1MgwMJzAjFLvPbETs4GBKlMsDQRTXVMs7+DYpljTG2SB+Nd+4ZnajMSngn5mBWl+5/JVM6Kzmk9TlAHkkUqT2UYQ8RZrJOlssN+ao3w41q5bWIOQ5dOy0OP1XwcujHuU7F8bs3uUOPOwARqW6RHL7Zr6AF7VlAo5a3iWvWbA+SaMgVaoUj7wmfPo5E3QY8gKWHFlzGqRcbHy/y+FKp+qDWAcJLHPMysE71o8DuXFiACYO/Ab3nUHsBvKmzwRXfkzgcKoUZ7B6IncT+ncjXaQRf0v+Lw7BGnciBNeEMCKv6nl1MhvSQvm1CIIjoHHx4BL6td7dwmuEIG3i7w8jq4Krm9V6yILSIOuya/Gb4zgKgAF5x6ZBSL8bIg9hzWqL
    LLM_OPENAI_API_KEY: AgCBye9iC19rwUwIU21JnaNY+c8alyrDNGRvpfTqEvVtmFgpDVD++O7EhIN83YGmuq0yPpGGBu7XprcXXzLqOi4vwPFOCEOXZ8Q1Rd0tIZWONUkeJGLgzxuOOQEVxE6+F/Y99kawEiY4j0O3CiFbYRw2kVYCBIlCSerD2zNapx7si/cafNJLXGWpYEkR9rYwW3D73OQaN/hJ7Qmv8xjF9CItLP/dY3du24x8weliOVsaZs45nGH24zJGz+WWlW3H8/gzVV3+3SYFXnppObIG+6rHgPJ2GfFl0fViXslALCXyNb4TNcCVHVMlP8PU5ANLCUpEuOItmBZ9+ETd6sZBi5yUJ5PRrdiaPB/cQw+Nzq+Fy59LTY1oHMsyf60TJ1/2gzZIztBKG/yCX/uq0HQDaDX+iH78/ubDSbBbd6uqWqsxpjHxBnXhUyqIZDueHn+moTOeDEfxljEzt+UqB4DTSnS6sKuza7D0KQAFc5gz9YBrYkGojHEEIli0OngaUsLKe08NrKwgbLMszlQjxGDR8iJZBNHsyFpwKVzPbZ5WG1ax2s1fZGu+lqkr/YdLjRZU46G61rql3noauodzLIl2VqWhf+kaUBREbJqiYG48hNaEEeO2KEDjUoICvW5sWNy/1b4xfpPXISSkqTsLZnEXyHQoHLG6KJTuccw2GAGWSpgm8TSQ2EHKdH5QFZPjWfHS9KS4V4nyXsxpeXn4kYldt3j9DUaYxY0ou6PkwX0CISe3OLCCCtCiiwwao2oO5ZL2W+HLEnJM0JshTxa7301vPT+2vLoe
  template:
    metadata:
      name: honcho-api-secret
      namespace: honcho
    type: Opaque
