---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: honcho-api-secret
  namespace: honcho
spec:
  encryptedData:
    DB_CONNECTION_URI: AgBemguKxOmbWccbM5Fu7kbM7FoeSCzPl98eeWqyP2D0ZowN9bYunATes/MEJApYrY5/L863x0dGAsG4AoEfXDoArxkS6BK06mgPVt3wGXw8gp5tDNiYvhlaGVIIWkpC4bQ3D+EUEbMc3xtPcmnwyxDBBlfY5mGVXZNBRr0DdSvtW3o1Pssp3fsyycu3D7+P1nqIo+QVkKC1cuwE3ZNLKAHUnwspv7ky6+F8lZVj6V/5WP0BqOzUOvCzvpvo6n2jYXG3A+7YYkGSa5M39TLsT0pn9lv1smU++XmbKyCPC1E8WIrydupmmGmrTbbxjBh7Sk17Ih8+h1dgrqImjpjUkmMEZxw6p59EWCDb8wJ0OWpprLxjn6eQx3EgPKkU2NwW0sMzWix45Z46Pw7izuPg8Cj8rB2K622tkyx0Kbi6liA45V7PM9WHPZ6LtiRqya304nMbK7zhjZIXlI2D3u6h8pW1skJSfe47NYFHDyH++DyT2hFxIQdAffl0aYaydod9UhH7G99+eS1oHzdXHncvfGnMoPjCSxvIFFvUcKkAqhM6RjbFlEC9pz9kJGF/72gQHlZ2tEh3LepRjSgwHQITexGvB0VjjkXu5iUE1XeQAUBooPa+ep9xMsZlriNW6Ps+XEvVXHscrrX/KzkOOeGX5jXr8zekYo2hsoQArOPNm3393cNUAi3BhvyT0rOff+5D7jHlBi69VEY6kWPhFDVPc4IxV1PZHdS0hOA1MXBHKVeZxJGfpVsVSO6+pOq6jVqifKJ+Sj/NeIavlA==
    LLM_OPENAI_API_KEY: AgBStXOzfcAU3X4Q2VYC16BTuxRy1kBDWfFtFi7MJ81Ko0cv7VcBACFqafTlFtAdpXASXRm92qvOyzhlfSSXw5C50dc2R+7IsIpISSVjynx3qPcNu4nnAYODozsh+aYTc+S8fWzdikqTUjsnfEQB9Myf4GOuZ6dFE/75E+2cira8ABCal99uwE460Pj5PaDJB0RwXkoYqDatQ4LieRHxAIktsMK0/OcbRvZ53j6lanUmFUFcsV89MeecgjW02pR11OI0OFC1z2EdWx4OvLp5E4pXtysYGoqEHuVgLxgfKyBz+Yg5gV2i1sDAnmsxU6m2IdOM26lFAWMiO3ILUqHwRtkXxu5qc9gEjCSaI3aFA+7yyYrWUjX2CLpFav6Ja1RF91U0xp2o1DYqfCZyXwoMuV5vjz1AWpxlhCuWJaRelvdeLM9AoK2LEoKQat/XjqCS6hQRu+G9NQn9SgNZStGJSqOwxBQgmRxXgWzaRZN9Mgi10t8kMXbDBDexOIg0cnC907N9RhL66j+fqeDZWDUxp6hbPod9UqEy+e9SnukJlIfv12UDAF5Xy8UoUpXnyh8RlugniZ2lbRp0/QODD7DN+NTm66ONW85+qkD7IZVTyATKSS890LZu47kT9cDqL+WROjRxAuauaVe0YouD0zbTL5OueEnBiau852Pya1XGZvNLqvt5xZ7mXaK3cJhUUJw6XfQUroU8iHkGUv6n58VVq+Ezl3gO9ZzI81ABSqurzukXfuyW63wOztpFH35t2jxFTYrUl128HO8LR572eMabOUxFgb/W
  template:
    metadata:
      name: honcho-api-secret
      namespace: honcho
    type: Opaque
