---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: faris-cloudflared-tunnel
spec:
  encryptedData:
    token: AgB9d7qZqvEmvRNFYIEPxCCXVOcZyJIt/fOc71Ds61ylhR7FEQC3QFkBB8fT4NxeALQZg3P8HsuxfTnmR4KAB2Bq4LXQhfoRR8iwVFlEL3qvZ5oJ9+lJEWahqEAIJHCW3q+Svox82PMqupNVDSVyWOaQVmd2ANOX7KBFekN4I4L92tneKSLFZmQ05VlFSbOaVdkEUqJjCop5zkdv4cxIMY99jvA2O/f8z9tF27hcyU4S/N3cFy78aErxF/OcfYgTTiCEF8Ozu4zDNwTSL2hud2X+aPQ7yFQ7zJMRRmG/u7WgysYXkDnq7CTrpf/bxbkwGVcakdHWCUIHlCiMd2XJDg/g1eNTFrga7f9ZIcuV42wWQqVVtQQZYIu8WyO0Ylfjz8eKQQkhrf8CIzeOjkEFDDhIWDM6BF6GzhRjGwNJ/f9iWkLRbukFIAHaHlQIHIv4n9EVLsi/SGja2ywz5UNT/v6LGhrHlbWxPhyx3hjgo4ht0bVOmrHb+PzF4dWYnkmVIEbnfpeH+DGR3UK5x/ALui4TV6caWZvz4qaPhjF6rDOS8SkC2ske6r20khL4Y7+NwEDHTCT2DlzXKfg6p3UzMPPyRm7t8NpphUdFUioQSs4CW01WfGaUE2Q0HiAlzMXuzBDkWxWPDDJQKt4C+8Gv4nqbPfvoRZEbs7j0TAJfsiQDGr1tarekTwHqI9+BHhN+nA7orV8ykzog/ZGptYYvYdJLaoUwgPNNVXLT+0ciF660NvF3zfw/Jxvv3orMI/DPv1z2BY3PU+V5vKYo6hVOF6B9xo3E8n5CxDCKf28K8IG/EUU2mMK6jPUcWOvT90IZSo+1Kgz2GfUK3ZeoIeV4suzKYs1AcTNMaGH4fXwIghB9LnjSFsQU2VFi3YfBHGspg0KM0eEbrDxgqROyg8Tx/xK3mVkSFgq6HV0M2xnOjuLOLk9PiZYasVX+
  template:
    metadata:
      name: cloudflared-token
      namespace: faris-cloudflared-tunnel
    type: Opaque
