---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: faris-cloudflared-tunnel
spec:
  encryptedData:
    token: AgAzzKjOb0ypsdIi4huuM9yzQ0IGL9TR/pLRSpMHVvYo5BCT9dyn0xGzM7LPdO791A41q7/nNoW920r2Y3xq1bOZxDBOk3EPWIImUUAXIIsIl/kmm/8HIMOls7UKTIY+keRfhfcwjIZJnYlrYiYSQahQ3vSBvJE3aIqLF7LAOEgUdvgwk1tAx0nmQCfnuKMncb5iRyHNJr5cBPB/JJE06iPmunTWnT0YrdvoLsTz8lbUG6ku3jiWlNWrei9cYfgaNWClLFbUDoUqPxzLgXc4eunwwqOdNw4w5QHDwbguL4oAMQXzhr9ARrlEXnHLQLRuyL6jHYbfuj9q8IHlBI/FZNI3HNzWIlBBXNqO9BV9NLu453GmpkdwAb+JOmv8PFEUOAUUpqQ5zXduM9XSEgMLCVHnsD7t+PZ/ixAwavUaLRghaF70FdqBduu73mfDEYT9xp+4BmqghF0Aq+MSSHmNyoMSfmsNjqjUS1q5YyjD4e666Ca9jWGzB89t3kU/wcu8n7Ewf5xUCxN47ftuMYARBb3+V8OKS726bGafylArNrJanKs6r7L6mg4gGs+rGCPgtg3hFjgrhFtoHskyAovbpDWAcsg1Ib6EfCvQqBINeNZwbkqEt82vMvN+pOQS8KGkF1mlaUAHT4shFu9oB0C5I3QHbLjy29CvBswr94FC2W89+xtiL7rDrOAh1/O/LT/TcjvX8uSZ7unlZ/6Jc7qkBnzJA8YXIp96UybXzkFH9ZijMKD39nQLaGwhMBHSXQ4qSCbbE6/g1IOmXfO0PCbTHipOrmoHkhEPojZXWfN1lEqax41GwSzskbOOnf/b6Xj5GYmZJrnp3UyDEiAAwPEOtRp5TB1Tpro+x5QVQDuvkIr6n2Qn2AmN3IqiuustW0xrUb6Ebmla9zO+ISX6+pr70AwYi0y01gzdyEJxvAvKdrOLZRTD71hfuAhp
  template:
    metadata:
      name: cloudflared-token
      namespace: faris-cloudflared-tunnel
    type: Opaque
