---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: faris-cloudflared-tunnel
spec:
  encryptedData:
    token: AgCdizPyX4PaYK5M6g9vSjuwi7/T8TPzq3ZEpWeMUn589+3cfzHqUzHpCaQbXGjfo5xJ+q7F/mvDEV3XGkmVj3mgQegF2FZkfCv59/MlKMvTINkKupFO4qOWANmE0nlpj6XYGRIqRDqW8+qQwAPzcNwRYrMvceTTMJDyRR8hsii9NENihoPGk2DmEjJeGEBTj8hysT+lJNGOMuwlSFYunedeAzMGYWuC0dGis6pTnx9h8taoAFqtwHxELjOg5xHh+8VNHpFkKhwES1nCvX7uYfSAyLvcj4sU1e9c32QbURZdAG1xkbvn1JGpuWfkZQgxZU0wC/lUddce9glUZaeBf1G6ApMB9IZqD/TzTrL/U53ppttHv+UL56hTrg7kin/Ub77IgEbDs9JU343W+qujwDeUr1P/6VO7rcqcgKDr6mFELXWQlmaUP4q45dSklzkPJ+tJWZmquvs6BExqYPr84Zxqytt0uqNqgtDE05/RF1hX9RUu+GXw9F3ICTUXn9XWoQRdn7EREsKKnZPgou6FiAgvoAXbRfpKeizUVq322Y93yikN9oETqyrBwv5OJabhbcE2OJjj0OFI1phJdUrl0G46+GkYm4O5VKm1WwBMiMu6OZV0ttlLuyrNrTljwPoIwz/utz5bAUMMxWmnbMP82/m69cwjxH0wZn1tvF1tzB9wsP0ibzsxjdASuH19lupCDuwIuFTeRtjgyVjUODfB3fb3+7w93sYYL9yEFqZeffjag8RP4o/Levc/ZDC30IRL+WyEHKcxNDPdG1wZxKkivwYHupQLIRV1/EqPDD48Fpk9sBTBJzzCPwlur5nAwMMzASZfJRs7bvGhkdgxLkzQ8BrHfHEsmGzH3GMRkR6PDBVl9Hxm08qMkCw544TVEFDTYUmyppEvjV9J3QXAKgJnIlBnNSZD0K6lnIyEpsn25VK1dez7ZjRAbL7D
  template:
    metadata:
      name: cloudflared-token
      namespace: faris-cloudflared-tunnel
    type: Opaque
