---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: kfo-website
spec:
  encryptedData:
    .dockerconfigjson: AgAHCqfCt05HgSSql7jtZOwp/QI8qdtHNXUjw5xSJYjT1xdes5GWiXL+ictf0Br5DFJltC5NuYqBttHbqgvL3P2CMtTRxcBnCCCiwJVqJGaOg4IZ9yzjx7IG/osqCtHzbXCn747s3hFccSF7vrX1vtSnui6ZlrjRmY1CF097FN6Eacbfx7YXiffgVqyBd2/Z53XXdNJ8urTwi0EMqqzF1cNweqgM8YclPVXwAWumAiVOWGkHExxrqd5mfxzuIChegdD6vOkbGKqUamgUTr0Bn/K6mp1b6YaMxT84aRBD7uTXH1DZySiTYtPfVEwC3AkbzYL6k7TTLc2mFPQjjo4hMYmSRrGFdmgi/PF7x49HNER6VYNIYdczAB8r0RHZepvvMBlPZLsahCebEAgC2Kjh85ubYVwY7xtOCI0i4muC1b7h7y+ho8TBzPgkRYbXGnQen2HclqsNRG7PA7IWwg3c3q46nd55J1fAsKkjby0xHU1UvGz02UOA6JURbWCeBhY4Cj6esYVBgfybUIt/alURGjDRURrj8kCKefhhKbn+HTtNVQv7l+1+mHKE2q8JxRnqsWKemkc+cht8x3cBj+ZH8W8n/XWuP8sT6lod8gddCU8T17DjKZCEel4t5sQI+vPkzTjJh5cCyfmeCQ67dAQKge3VG7vnH3V2vaZGtgd6HUJSkCQ5cOtIGzKBar3G/0vMEZJO80jjA6jPlXZA3naS00H5oUSEhgZE67V+HxCS77zCjFCyLN6WYWpTrIO8cWD8Mys//p0Iw/M4pm1jNdeIS944ha4vEfhzCCetbqYACNAXBTWYKpjUKFo6kV29PNZnwTJzTe5wSLU8nJD12RBpolajGgTqZHawKHpnPG99xMmkw4Pau9mNqdndaTkl4XS9bREakJ6VgNyp0rUh4BXQIP5D0ecist8n/EsAC0SdjOYT4AeLpn5PH1BaoZiIRlVuBvYmS5/QSyQ=
  template:
    metadata:
      name: ghcr-secret
      namespace: kfo-website
    type: kubernetes.io/dockerconfigjson
