---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgB4dqHwNT5wHXjDrkDX5E6hZMyH22RaSnqNXRJLMNJ0WhlZZhSandJOb7luO/N7nihlUlmIcfVbjzhDv4gJVjtmT9pXlNI/dS46XR7J7g7pQvBsOBW9Cy3OB1wfj80Mfo33FdRO8DPy0LRUYC+GwS4n+OLa0tSKaU/Pxfo0D0qHgQ4qN2LjisPMj8wsLZk+DgniO3mgo/1N+JyzKRJOouaW7lY0tjIWj8D3+zdDK75kwUqjrlfgiXG8+wtdnPf+9n7QeWZBjnJrl9mUSi5Belu17uvJ+V4EPQ3VEo+aGh0IvoDoZvGozxOzayCZ2bL+ECuugkrZ8xu0kwkB8r6J8Sluy0MCWK+iN3gUxaJAefouF+fr0yM8NHZfFCZSUOB2fNqKjxx0DsNa64/Jz9/KI9cjZt+51ij9MoE5JWtco++pj8uAqOKxY5QKi2ifAkEYs5u2w6fIWi0V1ERcVQu5APrxa5QyY7tsYq8lytdoXf9Y19ho2zFoqC927s1j/4rq+aDq9krOcFXCZ+PkKEBrWf9SR6SOphwcxfdq9z0p21mWYsmGYMcrE11DjUiyC2rljoxm8r++vFoq2Jop8+JYZzudsQI9MY/UQEwX7WxBliGGbnuFh3HnizS2e7Z9LfnD/JTY2xhNl7HXf4hNAcg3OAo3Q5cIki+MkfHIz31dIWntYIMSzJXrznYwwKH4kTeQoGIMKzQwpmK8odOGry0ADtdkYW59W3P/NMQqtEixGN7DNo4cx2lLBC2Zpq+GBc5lUdI7OGV1G0Ed9pPd9J3HdauOtQHUc95/kXJ4sFDDpOotXaYN4kAbNjc2S59hzGmNesbNdBPlvBFxwnhlLddSUnSKEe+2IEtvXNkWsujp9KZ4A0ORI6nYY+rgQEec1Qdsojd4oWYAo4IaAIlA4xThqbBeWTHipKHNZi9+bqekXpgWjFPpZo6stG1r0PMMiQy7QjDHYY1zbS4=
  template:
    metadata:
      name: ghcr-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
