apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: kfo-website-versioned
  namespace: kfo-website
spec:
  imageRepositoryRef:
    name: kfo-website
    namespace: kfo-website
  policy:
    alphabetical:
      order: desc
  filterTags:
    pattern: "^([0-9]{4}\\.[0-9]{2}\\.[0-9]{2}\\.[0-9]{4})$"
    extract: "$1"
