---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: kfo-website
  namespace: kfo-website
spec:
  filterTags:
    extract: $1
    pattern: ^([0-9]{4}\.[0-9]{2}\.[0-9]{2}\.[0-9]{4})$
  imageRepositoryRef:
    name: kfo-website
  policy:
    alphabetical:
      order: asc
