apiVersion: v1
kind: ConfigMap
metadata:
  name: firecrawl-config
  namespace: firecrawl
data:
  HOST: "0.0.0.0"
  PORT: "3002"
  REDIS_URL: "redis://redis:6379"
  REDIS_RATE_LIMIT_URL: "redis://redis:6379"
  PLAYWRIGHT_MICROSERVICE_URL: "http://playwright-service:3000"
  USE_DB_AUTHENTICATION: "false"
  ENV: "production"
  IS_KUBERNETES: "true"
  SEARXNG_ENDPOINT: "http://searxng.searxng.svc.cluster.local:8080"
