---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-admin-secret
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgCTRQo8Ep2f66EpTpcYjuS6b4JEDdEonkenCPplQzXX+D83/iTfGFzKamXpkHZLt0a4dz3APB42bazj7vThTVEDNcZR4ZLs3jX8HsTuPz1KskJ5ioxgKRaaN/hb9uO9vigdAeHialwM6UqzHP/qg0ZEuwv6dS3dlJwAmrLr72g4pzjeCQgXbUmQ7LmoKkxP4t8TJk1GbrEgymr4D+bqZKLpNyMt/m7nMcLSjksdgoESMeg4/Liyh11aZVyq7ItpiiubADZcPstxSlJEyRwJ5UDwhz7pEI7LLvCsb81110IUFpkn2niBMvpSBiTqtEz2AEC8M5ajY3uophaGh7cXBDI0rT91kkqWZZ1ahPjyadMIzKIdJz7IVuAQ+wHTVc9ca1e39XvuuJzRJ/Dr0h3hyZCPAH0byty8FR5lPxo0sKhT95IHjl0OkcLRG6TE/IaAIckswW0kbKZPNhCAbey97uvBn5guV6yWYUVoh45/p2tkVsuUZ6xSPFsjqArTJdlghGpOcuxKkrdDjpbujrjGjg+P4NHDLvDKE6Ag/Z96EthSrXIVBFf0iJiLm9BUFG0yDzV6rKwmg7GPWAu6hBPqAPlZe8lalo2qceWqDnpyDqlJTbSqycsj9K4wq7RcQ7QaepOcTrxg8suMnroxY6kByeQ9VhtLkfIdxN+c5DBnpeNAN7+/O0kX8lcnj9f9XTXMKk9IZV4z+7lluUmhm/1BlMYeHzTNzN2fj67oRPh2qJsSjytEaXlvE1/Meeo3wA==
  template:
    metadata:
      name: harbor-admin-secret
      namespace: harbor
    type: Opaque
