---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-pg-secret
  namespace: harbor
spec:
  encryptedData:
    password: AgBEfWj2Vg8vsbDUau58S9UZUdiTlfRJ3tDgBXXOSqpsYwUfNRfYZlV813wyDAt/1CXuvmJ4ughkI0IMYlUJsJ2xWv6xHTHT/kLZ7dlJm6O0SSSZcrOUZti5FTCNGpCfWk/jcDlwc6Sk80iXWosHcUCaalApJehqSxOB/gj6DhkGGQ1Qva64Uifj1duhuWh8vjBYXGjL7pefVrEv1+RWhyl8VMEm1qNQAbGeuWgpKQBp3xM6YCcfH39zbvAYjDUsyJ4hEFC+MxrgXePOqontmyabeTz/XU/4fzvTzaeCFNpeHoxmyE7zZjWjmkMr1rsF1P2klTrJBSdS41PiQDsX+fb3O00+KEhAk4w6gP5NugAO248JoCawLfQa8Ak4VJg4P/lb/bBSgQFY/bPOVEAglBch+TFrDIvXyhyhNrwX13yWdUWNAE/7DoiF2Q+7Jnq4fmoEBd0preCdtBCT1uj2RDe/CxxTvyZ/gBOuY2ogTgE1+qdICdn8xzZa2Zu9zkSRax33+xZMewOu28kCjz5kXuqB8w/gnO9z+tN4UTSMa7m8tQjWx/sq7HV4bPjrc+hIx/3delmVoVqDv/Bp6R41oPTzdvkLJfj9C7t8zzekMqqia2Y7hBJDtUnswKtp/ujM7GhfXZut50by9J12CTGxAGf5kDqTSnmLk6Ewmcaf8VPHrLnNgtgkSjhxMcFjqsChvt2Vnqm/2KH5Jjd6HtAikKYwWb7B7Ho5qQ4q7Lij4n9jcB0MxC97wrug7IDjaQ==
    username: AgBv1sjljGjZpvtHDqG36F0lFKP8TmD/TsKNCh0fU4nMd8TeczPXXEGSLIS6K+dfB7cxcOL7vgC6P26CBPZNVy6E6TBtVr7GvDM9uhKVIxhlyhnCVqf8JFYM073okeSn5og90IW5qlZ6L2F8hXDC7sjnfPuoZT3lfvyf1vqURDWHLZFqbdwsdk9qe5vOSNP8226reBm6OVg6NM7hlJ8Lll/nlBo+36nVAy22CrsaHZ+6gpF7KM5AeQjngsdz6vhO0ETjFXztZ1Xpwy8hOci+fv+xbUbaIsFlGWo0H8DkIOPPIGsGh+30JLqmfZ6xOf4TF9KCEFj/5ouIPzMSEEt/mLKpmjaE3XJx9pvfujHtci2T542kzpY3OF4D5YqliNDVzr8qwOnsO2swpO+dFNuE7DHSQ9vp3IENg82j19CYipiB06/CPzAZZ/OZMEszpAAbNZT9MvGTL7GDF2caKYNEu3kqJSDNOH0ynn+gCDmgN08mdy0NpAwwhq5h90/s8yNw/R1rXeq0nMc4+gugrgjr9F4SI7Fk9Qt95VmztPnsMRwl5gRNmQUJTeCwhs8L5w9UoaFY5aShBc73oU0+jJZaXb9R9e9XT/Mqm+1DtU2AEX8xFB6hmQDijMbDoicXdzTzQ00cz8dSD1NjaT2Oc95j2jbvtFPMelaG0aWDXqcigqCSwxcBAvx1QOGnbJh0+rJ2FwVTluzYjmc=
  template:
    metadata:
      name: harbor-pg-secret
      namespace: harbor
    type: Opaque
